apiVersion: apps/v1
kind: Deployment
metadata:
  name: burn-fix
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 0
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: burn-fix
  template:
    metadata:
      labels:
        app: burn-fix
    spec:
      containers:
      - name: burn-fix
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:tools-dev-941f0b2
        env:
        - name: SOLANA_ENDPOINT
          value: https://holaplex-main-9e4a.mainnet.rpcpool.com
        - name: RUST_LOG
          value: debug
        - name: BATCH_SIZE
          value: "100000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash", "-c"]
        args: ["./bin/burn-fix"]
