apiVersion: apps/v1
kind: Deployment
metadata:
  name: geyser-consumer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: geyser-consumer
  template:
    metadata:
      labels:
        app: geyser-consumer
    spec:
      containers:
      - name: geyser-consumer
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:geyser-consumer-dev-5b5ca37
        envFrom:
        - configMapRef:
            name: indexer-config
        - secretRef:
            name: meili-creds
        - secretRef:
            name: amqp-creds
        - secretRef:
            name: dialect-creds
        env:
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash","-c"]
        args: ["./bin/holaplex-indexer-geyser --network=mainnet --startup=normal"]
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
      - name: geyser-consumer-startup
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:geyser-consumer-dev-5b5ca37
        envFrom:
        - configMapRef:
            name: indexer-config
        - secretRef:
            name: meili-creds
        - secretRef:
            name: amqp-creds
        - secretRef:
            name: dialect-creds
        env:
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash","-c"]
        args: ["./bin/holaplex-indexer-geyser --network=mainnet --startup=all"]
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
      dnsConfig:
        options:
        - name: ndots
          value: "3"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
