apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: validator
  template:
    spec:
      containers:
      - name: validator
      nodeSelector:
        validator: "true"
    metadata:
      labels:
        app: validator
    spec:
      initContainers:
        - name: geyser-plugin-loader
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["while [[ ! -f /geyser/libholaplex_indexer_rabbitmq_geyser.so ]];do echo -e 'waiting for geyser plugin\nCopy from local using:\n kubectl cp -c geyser-plugin-loader libholaplex_indexer_rabbitmq_geyser.so mainnet-solana/validator_pod_name:/geyser';sleep 10;done;rm -f /ledger/ledger.lock"]
          volumeMounts:
          - name: geyser-plugin
            mountPath: /geyser
      containers:
      - image: solanalabs/solana:v1.10.38
        name: watchtower
        command: ["solana-watchtower"]
        envFrom:
        - configMapRef:
            name: validator-config
        volumeMounts:
        - name: ca-certificates
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
      - image: solanalabs/solana:v1.10.38
        resources:
          limits:
            memory: "240Gi"
            cpu: "30000m"
          requests:
            memory: "186Gi"
            cpu: "8000m"
        imagePullPolicy: IfNotPresent
        name: validator
        envFrom:
        - configMapRef:
            name: validator-config
        command: ["/bin/sh", "-c"]
        args: ["/root/startup.sh"]
        ports:
        - containerPort: 10899
          name: rpc
          protocol: TCP
        - containerPort: 10900
          name: rpc-ws
          protocol: TCP
        volumeMounts:
        - name: ca-certificates
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
        - name: validator-keypairs
          mountPath: /root/validator-keypair.json
          subPath: validator-keypair.json
        - name: geyser-plugin-config
          mountPath: /root/geyser-config.json
          subPath: geyser-config.json
        - name: startup
          mountPath: /root/startup.sh
          subPath: startup.sh
        - name: validator-keypairs
          mountPath: /root/vote-account-keypair.json
          subPath: vote-account-keypair.json
        - name: ledger-storage
          mountPath: /ledger
        - name: geyser-plugin
          mountPath: /geyser
        - name: accounts-storage
          mountPath: /root/accounts
      volumes:
        - name: startup
          configMap:
            name: startup-script
            defaultMode: 0755
        - name: ca-certificates
          configMap:
            name: ca-certificates
        - name: validator-keypairs
          configMap:
            name: validator-keypairs
        - name: geyser-plugin-config
          configMap:
            name: geyser-plugin-config
        - name: ledger-storage
          persistentVolumeClaim:
            claimName: validator-data-pvc
        - name: geyser-plugin
          persistentVolumeClaim:
            claimName: geyser-plugin-data-pvc
        - name: accounts-storage
          emptyDir:
            medium: Memory
