apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: wonka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wonka
  template:
    metadata:
      labels:
        app: wonka
    spec:
      containers:
      - name: wonka
        envFrom:
        - configMapRef:
            name: config
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/wonka:main-dfd7c6b
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: tmp-storage
            mountPath: /app/tmp
      volumes:
        - name: tmp-storage
          persistentVolumeClaim:
            claimName: wonka-tmp-files-pvc
