apiVersion: batch/v1
kind: CronJob
metadata:
  name: 30d-collection-trends
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: "57 23 * * *"
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: 30d-collection-trends
        spec:
          restartPolicy: OnFailure
          containers:
          - name: psql
            image: docker.io/bitnami/postgresql:14-debian-10
            env:
            - name: REPO_URL
              value: https://github.com/holaplex/kubes
            - name: GIT_BRANCH
              value: dev
            - name: REPO_PATH
              value: indexer/mainnet/app/jobs/migrations/2022-09-19-190727_update_collection_trends_30d_floor_price_sales_count/up.sql
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-url
                  key: DATABASE_WRITE_URL
                  optional: false
            command: ["/bin/bash","-c"]
            args: ["/script/psql-run.sh"]
            securityContext:
              allowPrivilegeEscalation: false
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: script
              mountPath: /script/psql-run.sh
              subPath: run.sh
          dnsConfig:
            options:
            - name: ndots
              value: "3"
          volumes:
          - name: script
            configMap:
              name: psql-run-script
              defaultMode: 0777
