apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-run-script
data:
  run.sh: |
   #!/bin/bash
   RAW_URL=$(echo $REPO_URL | sed 's/www\.//g' | sed 's/github\.com/raw\.githubusercontent\.com/g')
   cd /tmp && \
   curl --silent --output migration.sql "$RAW_URL/$GIT_BRANCH/$REPO_PATH" && \
   psql $DATABASE_URL -f migration.sql
