apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-holaplex
  namespace: argocd
spec:
  project: canary-holaplex
  source:
    repoURL: https://github.com/holaplex/kubes.git
    targetRevision: canary
    path: holaplex/app
  destination:
    server: https://kubernetes.default.svc
    namespace: canary-holaplex
