apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
data:
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  SSL_CERT_DIR: /etc/ssl/certs
  SOLANA_NETWORK: devnet
  SOLANA_SNAPSHOT_COMPRESSION: none
  RPC_PORT: "10899"
  SOLANA_METRICS_CONFIG: "host=http://influxdb-exporter.monitoring:9122,db=devnet,u=solana,p=whatever"
  URL: https://api.devnet.solana.com

