apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: hola-signer
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hola-signer
  template:
    metadata:
      labels:
        app: hola-signer
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: hola-config
        name: frontend
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/holaplex:signer-main-a6eff4a
        imagePullPolicy: IfNotPresent
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            secretKeyRef:
              name: amqp-creds
              key: AMQP_URL
              optional: false
