apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: geyser-consumer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: geyser-consumer
  template:
    metadata:
      labels:
        app: geyser-consumer
    spec:
      containers:
      - name: geyser-consumer
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:geyser-consumer-dev-8dfa6ec
        env:
        - name: AMQP_URL
          valueFrom:
            secretKeyRef:
              name: amqp-creds
              key: AMQP_URL
              optional: false
        - name: DIALECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: dialect-creds
              key: DIALECT_API_KEY
              optional: false
        - name: STAGING
          value: ""
        - name: DIALECT_API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dialect-creds
              key: DIALECT_API_ENDPOINT
              optional: false
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash","-c"]
        args: ["./bin/holaplex-indexer-geyser --network=mainnet --startup=normal --dialect-api-key $DIALECT_API_KEY --dialect-api-endpoint $DIALECT_API_ENDPOINT & ./bin/holaplex-indexer-geyser --network=mainnet --startup=all --dialect-api-key $DIALECT_API_KEY --dialect-api-endpoint $DIALECT_API_ENDPOINT "]
        volumeMounts:
        - name: indexer-config
          mountPath: .env.local
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
      dnsConfig:
        options:
        - name: ndots
          value: "3"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: indexer-config
          configMap:
            name: indexer-config
