apiVersion: batch/v1
kind: CronJob
metadata:
  name: legacy-storefronts
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: legacy-storefronts
        spec:
          restartPolicy: OnFailure
          containers:
          - name: legacy-storefronts
            image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:legacy-storefronts-dev-b4c464f
            envFrom:
              - configMapRef:
                  name: indexer-config
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-url
                  key: DATABASE_WRITE_URL
                  optional: false
            - name: RUST_LOG
              value: debug
            command: ["/bin/bash","-c"]
            args: ["./bin/holaplex-indexer-legacy-storefronts"]
            securityContext:
              allowPrivilegeEscalation: false
            imagePullPolicy: IfNotPresent
          dnsConfig:
            options:
            - name: ndots
              value: "3"
