apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    reloader.stakater.com/auto: "true"
    argocd.argoproj.io/hook: PreSync
spec:
  spec:
    restartPolicy: OnFailure
    containers:
    - name: diesel-migrator
      image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:migrator-dev-4b3ab2e
      envFrom:
        - configMapRef:
            name: indexer-config
      env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: postgres-creds-url
            key: DATABASE_WRITE_URL
            optional: false
      - name: RUST_LOG
        value: debug
      command: ["/bin/bash","-c"]
      args: ["./bin/holaplex-indexer-migrator"]
      securityContext:
        allowPrivilegeEscalation: false
      imagePullPolicy: IfNotPresent
    dnsConfig:
      options:
      - name: ndots
        value: "3"
