apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: search-consumer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: search-consumer
  template:
    metadata:
      labels:
        app: search-consumer
    spec:
      containers:
      - name: search-consumer
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:search-consumer-master-3b15928
        env:
        - name: AMQP_URL
          valueFrom:
            secretKeyRef:
              name: amqp-creds
              key: AMQP_URL
              optional: false
        - name: MEILI_KEY
          valueFrom:
            secretKeyRef:
              name: meili-creds
              key: MEILI_KEY
              optional: false
        - name: MEILI_URL
          valueFrom:
            secretKeyRef:
              name: meili-creds
              key: MEILI_URL
              optional: false
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash","-c"]
        args: ["./bin/holaplex-indexer-search --sender mainnet"]
        volumeMounts:
        - name: indexer-config
          mountPath: .env.local
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
      dnsConfig:
        options:
        - name: ndots
          value: "3"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: indexer-config
          configMap:
            name: indexer-config
