apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-consumer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: search-consumer
  template:
    metadata:
      labels:
        app: search-consumer
    spec:
      containers:
      - name: search-consumer
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:search-consumer-dev-a1b874a
        envFrom:
        - configMapRef:
            name: indexer-config
        - secretRef:
            name: meili-creds
        - secretRef:
            name: amqp-creds
        - secretRef:
            name: dialect-creds
        env:
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash","-c"]
        args: ["./bin/holaplex-indexer-search --sender mainnet"]
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 2000m
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
      dnsConfig:
        options:
        - name: ndots
          value: "3"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
