apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anshul-indexer
  namespace: argocd
  annotations:
spec:
  project: anshul-indexer
  source:
    repoURL: https://github.com/holaplex/kubes.git
    targetRevision: anshul/multi-spl-token
    path: indexer/app
  destination:
    server: https://kubernetes.default.svc
    namespace: anshul-indexer
