apiVersion: apps/v1
kind: Deployment
metadata:
  name: slot-reindex
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 0
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: slot-reindex
  template:
    metadata:
      labels:
        app: slot-reindex
    spec:
      containers:
      - name: slot-reindex
        image: mpwsh/indexer-block-reindex:v0.2
        envFrom:
        - secretRef:
            name: alchemy-solana
        - configMapRef:
            name: indexer-config
        - secretRef:
            name: meili-creds
        - secretRef:
            name: amqp-creds
        - secretRef:
            name: dialect-creds
        - configMapRef:
            name: reindex-config
        env:
        - name: RUST_LOG
          value: info
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds-url
              key: DATABASE_WRITE_URL
              optional: false
        command: ["/bin/bash","-c"]
        args: ["echo $(date): starting! && ./bin/slot_reindex reindex --network mainnet --selector-config /etc/programs.json --sender reindex && echo $(date): Completed all blocks && sleep infinity"]
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        volumeMounts:
        - name: reindex-programs-config
          mountPath: /etc/programs.json
          subPath: programs.json
      volumes:
      - name: reindex-programs-config
        configMap:
          name: reindex-programs-config   
      dnsConfig:
        options:
        - name: ndots
          value: "3"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
