apiVersion: v1
data:
  programs.json: |
    {
      "programs": [
        "RwDDvPp7ta9qqUwxbBfShsNreBaSsKvFcHzMxfBC3Ki"
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: reindex-programs-config
