apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-cm-factory
  namespace: argocd
spec:
  project: stage-cm-factory
  source:
    repoURL: https://github.com/holaplex/kubes.git
    targetRevision: dev
    path: cm-factory/app
  destination:
    server: https://kubernetes.default.svc
    namespace: stage-cm-factory
