apiVersion: v1
data:
  config.toml: |
    #Possible values -- debug, info, warn, error
    log_level = "warn"
    #port for the server to listen on
    port = 3030
    #CPU Threads for actix
    workers = 4
    #timeout when contacting listed origins
    req_timeout = 600
    #Limit response size from your origins
    max_body_size_bytes = 200000000 # 200 MB
    #For load balancer liveness Probe
    health_endpoint = "/health"
    #User agent should be <name>/<version>
    user_agent = "imgopt/0.2.2"
    #use full path if possible
    storage_path = "/home/imgopt/data"

    #Limit which width scaling options are available (optional)
    allowed_sizes = [ 0, 50, 100, 200, 400, 500, 600, 800, 700, 900, 1000, 1100, 1200, 1300, 1400, 1500 ]

    #Skip certain images from processing (optional)
    #skip_list = ["bafybeih6zvkw6fenaprelv45b4zjzazi3mvogvkq6ws75ywyphjk4iyqwi"]
    #Enable '?url=' query parameter
    allow_any_origin = true
    kvstore_uri = "http://smol-kv.assets.svc:5050"
    #Skip the following urls when using '?url=' parameter
    url_deny_list = ["https://google.com/search", "http://localhost", "https://api.stepn.com/", "https://example.com/", "http://127.0.0.1",  "https://arweave.net/%20#"]
    #Number of retries when downloading an asset
    max_retries = 10

    #max age header for twitter responses (in seconds) (optional)
    twitter.cache.max_age = 86400 #24 hours

    cloudfront.distribution_id = "E247IMV0ZDDH9A"

    #origins
    [[origins]]
    name = "ipfs"
    endpoint = "https://ipfs.io/ipfs"
    cache.max_age = 31536000

    [[origins]]
    name = "arweave"
    endpoint = "https://arweave.net"
    cache.max_age = 31536000

kind: ConfigMap
metadata:
  name: imgopt-config
