apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-wonka
  namespace: argocd
spec:
  project: stage-wonka
  source:
    repoURL: https://github.com/holaplex/kubes.git
    targetRevision: dev
    path: wonka/app
  destination:
    server: https://kubernetes.default.svc
    namespace: stage-wonka
