name: Remote build

on:
  push:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  build:
    name: Updating deployment manifests
    if: ${{ !contains(github.event.head_commit.message, '#k8s') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Update deployments image versions
        run: |
            git_branch=${GITHUB_REF##*/}
            repo=candy-machine-factory
            url=https://${{ secrets.ACTIONS_TOKEN}}@github.com/holaplex/$repo
            git_hash=$(git ls-remote $url $git_branch| cut -c1-7)
            app=cm-factory
            deployment_file="./$app/app/deployment.yaml"
            version=$(cat $deployment_file | grep -i image\: | head -n1 | awk {'print $2'} | cut -d: -f2)
            echo "Updating ${app} deployment with new image tag"
            sed -i "s/$version/$git_branch-$git_hash/" $deployment_file

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN}}
          commit_message: Updated deployment image version
